dependencies:
  # -<organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.0'
dotenv: .env
networks:
  sepolia:
    host: https://sepolia.infura.io/v3/761d2363bdb147f4babc971dd1a4c921
    verify: true
    etherscan:
      token: ${ETHERSCAN_TOKEN}
  ganache-local:
    verify: false
wallets:
  from_key: ${PRIVATE_KEY}