dependencies:
  # -<organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.0'
dotenv: .env
networks:
  sepolia:
    host: https://sepolia.infura.io/v3/${WEB3_INFURA_PROJECT_ID}
    chainid: 11155111
    explorer: https://api-sepolia.etherscan.io/api
    etherscan:
      token: ${ETHERSCAN_TOKEN}
  ganache-local:
    verify: false
wallets:
  from_key: ${PRIVATE_KEY}