dependencies:
  # -<organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.0'
dotenv: .env
networks:
  sepolia:
    verify: True
    etherscan_token: ${ETHERSCAN_TOKEN}
wallets:
  from_key: ${PRIVATE_KEY}